#pragma once
#include "../TrainingFramework/stdafx.h"

#include "Leader/TheCharismaticSong.h"
#include "Leader/TheCloakedSage.h"
#include "Leader/TheDivineArrow.h"
#include "Leader/TheFistOfReason.h"
#include "Leader/TheProtectingHorn.h"

//#include "Monster/AbyssQueen"
//#include "Monster/AnuranCauldron"
//#include "Monster/ArticAries"
//#include "Monster/Bloodwing"
//#include "Monster/CorruptedSabretooth"
//#include "Monster/CrownedSerpent"
//#include "Monster/DarkDragonKing"
//#include "Monster/Dracos"
//#include "Monster/Malamammoth"
//#include "Monster/MegaSlime"
//#include "Monster/Orthus"
//#include "Monster/RexMajor"
//#include "Monster/Terratuga"
//#include "Monster/TitanWyvern"
//#include "Monster/WarwornOwlbear"
//
#include "Hero/BadAxe.h"
#include "Hero/BearClaw.h"
#include "Hero/BearyWise.h"
#include "Hero/FuryKnuckle.h"
#include "Hero/HeavyBear.h"
#include "Hero/PanChucks.h"
#include "Hero/QiBear.h"
#include "Hero/ToughTeddy.h"
//#include "Hero/DodgyDealer"
//#include "Hero/FuzzyCheeks"
//#include "Hero/GreedyCheeks"
//#include "Hero/LuckyBucky"
//#include "Hero/MellowDee"
//#include "Hero/NappingNibbles"
//#include "Hero/Peanut"
//#include "Hero/TipsyTootie"
//#include "Hero/CalmingVoice"
//#include "Hero/GuidingLight"
//#include "Hero/HolyCurselifter"
//#include "Hero/IronResolve"
//#include "Hero/MightyBlade"
//#include "Hero/RadiantHorn"
//#include "Hero/VibrantGlow"
//#include "Hero/WiseShield"
//#include "Hero/Bullseye"
//#include "Hero/Hook"
//#include "Hero/LookieRookie"
//#include "Hero/QuickDraw"
//#include "Hero/SeriousGrey"
//#include "Hero/SharpFox"
//#include "Hero/Wildshot"
//#include "Hero/WilyRed"
//#include "Hero/KitNapper"
//#include "Hero/Meowzio"
//#include "Hero/PlunderingPuma"
//#include "Hero/Shurikitty"
//#include "Hero/SilentShadow"
//#include "Hero/SlipperyPaws"
//#include "Hero/SlyPickings"
//#include "Hero/SmoothMimimeow"
//#include "Hero/BunBun"
//#include "Hero/Buttons"
//#include "Hero/Fluffy"
//#include "Hero/Hopper"
//#include "Hero/Snowball"
//#include "Hero/Spooky"
//#include "Hero/Whiskers"
//#include "Hero/Wiggles"
//
//#include "Equip/BardMask"
//#include "Equip/DecoyDoll"
//#include "Equip/FighterMask"
//#include "Equip/GuardianMask"
//#include "Equip/ParticularlyRustyCoin"
//#include "Equip/RangerMask"
//#include "Equip/ReallyBigRing"
//#include "Equip/ThiefMask"
//#include "Equip/WizardMask"
//#include "Equip/CurseoftheSnake'sEyes"
//#include "Equip/SealingKey"
//#include "Equip/SuspiciouslyShinyCoin"
//
//#include "Modify/Modifier+1/-3"
//#include "Modify/Modifier+2/-2"
//#include "Modify/Modifier+3/-1"
//#include "Modify/Modifier+4"
//#include "Modify/Modifier-4"
//
//#include "Spell/CalltotheFallen"
//#include "Spell/CriticalBoost"
//#include "Spell/DestructiveSpell"
//#include "Spell/EnchantedSpell"
//#include "Spell/EntanglingTrap"
//#include "Spell/ForcedExchange"
//#include "Spell/ForcefulWinds"
//#include "Spell/WindsofChange"
//
//#include "Challenge"











